name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    name: ${{ matrix.job.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - { name: Build, command: "build --locked" }
          - { name: Format, command: "fmt --all -- --check" }
          - { name: Lint, command: "clippy -- -D warnings" }
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo ${{ matrix.job.command }}
